# Generated by Django 6.0.3 on 2026-05-16 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("FX", "fixed"), ("PR", "percent")],
                        default="FX",
                        max_length=2,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=7)),
                ("valid_from", models.DateTimeField(db_index=True)),
                ("valid_to", models.DateTimeField(db_index=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("once_per_user", models.BooleanField(default=False)),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "PromoCode",
                "verbose_name_plural": "PromoCodes",
                "db_table": "promocodes",
            },
        ),
    ]
