# Generated by Django 6.0.3 on 2026-05-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': True, 'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
